[programs.localnet]
gem_bank = "AAchXqCceMw6vCgo2BL1JhdjBLNGUmf3rpbhMeaUt1dM"
gem_farm = "6WLTpV8DtL75Tn81Z82RMzp9qtK8TmxLkZkjY4eRTREf"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/staking.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

#[test]
#startup_wait = 100000

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./tests/programs/metaplex_token_metadata.so"